### ISSUE TITLE
styles={{border: "none"}}

### ISSUE THREAD

**Issue by prographo** [robbestad/react-iframe#52] opened 2019-05-07 16:08 UTC
Is not respected.

**Comment by OscarCR88** [comment] 2019-05-10 21:19
I was able to go over it by adding a className with border: none
like this:
```
<Iframe url="some url"
        width="100%"
        height="10780px"
        id="myId"
        loading="Loading...."
        className="myClassname"
        display="initial"
        position="relative"
        allowFullScreen
        className="myClassname"/>
```

and then in my css

```
.myClassname{
border:none
}
```

**Comment by denizdogan** [comment] 2019-11-12 11:37
Duplicate of #51  I think

**Closed** 2022-09-27 06:16 UTC
